# DO NOT EDIT MANUALLY - generated by DOGMA prompt rector - 2025-11-17T00:00:00Z
from flask import Flask, jsonify, request
import sys
from pathlib import Path

# allow importing shared/ by adding repo root to sys.path
ROOT = str(Path(__file__).resolve().parents[2])
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from shared.utils.logger import get_logger
from shared.storage.s3_client import S3Client
from shared.database.supabase_client import SupabaseClient


def create_app():
    app = Flask(__name__)
    logger = get_logger('social-service')

    @app.route('/')
    def health():
        return jsonify({"status": "social-service ok"})

    @app.route('/post', methods=['POST'])
    def post():
        payload = request.json or {}
        logger.info('received post: %s', payload)
        return jsonify({"posted": True, "payload": payload})

    @app.route('/upload')
    def upload():
        key = request.args.get('key', 'social.txt')
        s3 = S3Client()
        ok = s3.upload(key, b"social")
        return jsonify({"uploaded": bool(ok), "key": key})

    @app.route('/dbping')
    def dbping():
        client = SupabaseClient()
        return jsonify({"ok": client.ping()})

    return app


if __name__ == '__main__':
    create_app().run(host='0.0.0.0', port=8000)
