# DO NOT EDIT MANUALLY - generated by DOGMA prompt rector - 2025-11-17T00:00:00Z
"""Placeholder supabase client wrapper"""
import os


class SupabaseClient:
    def __init__(self, url=None, key=None):
        self.url = url or os.getenv('SUPABASE_URL')
        self.key = key or os.getenv('SUPABASE_KEY')

    def ping(self):
        return bool(self.url and self.key)
