# DO NOT EDIT MANUALLY - generated by DOGMA prompt rector - 2025-11-17T00:00:00Z
from flask import Flask, jsonify, request
import os
import sys
from pathlib import Path

# allow importing shared/ by adding repo root to sys.path
ROOT = str(Path(__file__).resolve().parents[2])
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from shared.storage.s3_client import S3Client
from shared.database.supabase_client import SupabaseClient


def create_app():
    app = Flask(__name__)

    @app.route('/')
    def health():
        return jsonify({"status": "ml-service ok"})

    @app.route('/predict', methods=['POST'])
    def predict():
        data = request.json or {}
        # placeholder prediction logic
        return jsonify({"prediction": "positive", "input": data})

    @app.route('/upload')
    def upload():
        key = request.args.get('key', 'test.txt')
        s3 = S3Client()
        ok = s3.upload(key, b"placeholder")
        return jsonify({"uploaded": bool(ok), "key": key})

    @app.route('/dbping')
    def dbping():
        client = SupabaseClient()
        return jsonify({"ok": client.ping()})

    return app


if __name__ == '__main__':
    create_app().run(host='0.0.0.0', port=8000)
