# DO NOT EDIT MANUALLY - generated by DOGMA prompt rector - 2025-11-17T00:00:00Z
from flask import Flask, jsonify, request
import sys
from pathlib import Path

# allow importing shared/ by adding repo root to sys.path
ROOT = str(Path(__file__).resolve().parents[2])
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from shared.utils.logger import get_logger
from shared.database.supabase_client import SupabaseClient


def create_app():
    app = Flask(__name__)
    logger = get_logger('ads-service')

    @app.route('/')
    def health():
        return jsonify({"status": "ads-service ok"})

    @app.route('/click', methods=['POST'])
    def click():
        payload = request.json or {}
        logger.info('click: %s', payload)
        return jsonify({"received": True, "payload": payload})

    @app.route('/dbping')
    def dbping():
        client = SupabaseClient()
        return jsonify({"ok": client.ping()})

    return app


if __name__ == '__main__':
    create_app().run(host='0.0.0.0', port=8000)
