# DO NOT EDIT MANUALLY - generated by DOGMA prompt rector - 2025-11-17T00:00:00Z
FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-m", "http.server", "8000"]
# e2b devops Dockerfile - no secrets here
FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
