#!/usr/bin/env bash
# DO NOT EDIT MANUALLY - generated by DOGMA prompt rector - 2025-11-17T00:00:00Z
echo "Setup script placeholder - run INSTALLATION.md steps manually"
#!/usr/bin/env bash
set -euo pipefail
echo "[+] Setting up development environment (local only)"
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt || true
echo "[+] Setup complete. Run: docker-compose up --build"
